// ABOUTME: Columnar transposition cipher: text written in rows is read out by keyword-ordered columns.
// ABOUTME: Includes a breaker that searches every column order up to a key length and ranks by bigram fitness.
// SPDX-FileCopyrightText: 2026 Michel Oosterhof
// SPDX-License-Identifier: BSD-3-Clause
import { normalizeKey, type Mode } from "./cipher";
import { scoreText } from "./solve";

const CODE_A = 65;
const MAX_KEY_LENGTH = 7;

// Candidates whose fitness is this close to the best are ranked by key length
// instead, so the true length beats longer orders that overfit.
const FITNESS_EPSILON = 0.05;

export interface ColumnarCandidate {
  /** Canonical keyword (ABC... ranks) that reproduces the recovered column order. */
  key: string;
  keyLength: number;
  /** Average bigram log10 probability of the decrypted text; higher is more English-like. */
  fitness: number;
  plaintext: string;
}

/** Column indices in the order the keyword reads them out; repeated letters rank left to right. */
function columnOrder(key: string): number[] {
  return normalizeKey(key)
    .map((value, index) => ({ value, index }))
    .sort((a, b) => a.value - b.value || a.index - b.index)
    .map((entry) => entry.index);
}

/** Height of each writing-order column when the last row is incomplete. */
function columnHeights(length: number, columns: number): number[] {
  const base = Math.floor(length / columns);
  const extra = length % columns;
  return Array.from({ length: columns }, (_, c) => base + (c < extra ? 1 : 0));
}

function decryptWithOrder(chars: string[], order: number[]): string {
  const columns = order.length;
  const heights = columnHeights(chars.length, columns);
  const slices = new Array<string[]>(columns);
  let offset = 0;
  for (const column of order) {
    slices[column] = chars.slice(offset, offset + heights[column]);
    offset += heights[column];
  }
  const result: string[] = [];
  const tallest = Math.max(...heights);
  for (let row = 0; row < tallest; row += 1) {
    for (let column = 0; column < columns; column += 1) {
      if (row < heights[column]) {
        result.push(slices[column][row]);
      }
    }
  }
  return result.join("");
}

/**
 * Encrypts or decrypts the columnar transposition cipher. The text is written
 * in rows under the keyword and the columns are read out in the alphabetical
 * order of the keyword letters; the last row may be incomplete (no padding).
 * Every character takes part, so spaces and punctuation move too.
 */
export function columnarTransposition(
  text: string,
  key: string,
  mode: Mode,
): string {
  const order = columnOrder(key);
  const chars = [...text];
  if (mode === "decrypt") {
    return decryptWithOrder(chars, order);
  }
  const columns = order.length;
  return order
    .map((column) => {
      const slice: string[] = [];
      for (let i = column; i < chars.length; i += columns) {
        slice.push(chars[i]);
      }
      return slice.join("");
    })
    .join("");
}

/** Every permutation of 0..size-1, generated by Heap's algorithm. */
function* permutations(size: number): Generator<number[]> {
  const items = Array.from({ length: size }, (_, i) => i);
  const stack = new Array<number>(size).fill(0);
  yield [...items];
  let i = 0;
  while (i < size) {
    if (stack[i] < i) {
      const swap = i % 2 === 0 ? 0 : stack[i];
      [items[swap], items[i]] = [items[i], items[swap]];
      yield [...items];
      stack[i] += 1;
      i = 0;
    } else {
      stack[i] = 0;
      i += 1;
    }
  }
}

/**
 * Breaks a columnar transposition by trying every column order for each key
 * length up to maxKeyLength, keeping the best order per length and ranking the
 * lengths by how English-like the decryption is. The recovered key is the
 * canonical keyword the tool above can decrypt with.
 */
export function breakColumnar(
  text: string,
  maxKeyLength = MAX_KEY_LENGTH,
): ColumnarCandidate[] {
  const chars = [...text];
  const longest = Math.max(
    2,
    Math.min(maxKeyLength, Math.floor(chars.length / 2)),
  );
  const candidates: ColumnarCandidate[] = [];
  for (let columns = 2; columns <= longest; columns += 1) {
    let best: { order: number[]; fitness: number; plaintext: string } | null =
      null;
    for (const order of permutations(columns)) {
      const plaintext = decryptWithOrder(chars, order);
      const fitness = scoreText(plaintext);
      if (best === null || fitness > best.fitness) {
        best = { order: [...order], fitness, plaintext };
      }
    }
    if (best !== null) {
      const letters = new Array<string>(columns);
      best.order.forEach((column, rank) => {
        letters[column] = String.fromCharCode(CODE_A + rank);
      });
      candidates.push({
        key: letters.join(""),
        keyLength: columns,
        fitness: best.fitness,
        plaintext: best.plaintext,
      });
    }
  }
  const top = Math.max(...candidates.map((c) => c.fitness));
  return candidates.sort((a, b) => {
    const aNearTop = a.fitness >= top - FITNESS_EPSILON;
    const bNearTop = b.fitness >= top - FITNESS_EPSILON;
    if (aNearTop && bNearTop) {
      return a.keyLength - b.keyLength;
    }
    if (aNearTop !== bNearTop) {
      return aNearTop ? -1 : 1;
    }
    return b.fitness - a.fitness;
  });
}
